cors:
    originsPatterns: http://localhost:8080
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_api_with_spring_boot
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: true
springdoc:
  paths-to-match:
    - /auth/**
    - /api/**
  swagger-ui:
    use-root-path: true
